language: php

php: [5.5, 5.6, 7.0, 7.1]

env:
  - SYMFONY_FRAMEWORK=2.8.*
  - SYMFONY_FRAMEWORK=3.0.*
  - SYMFONY_FRAMEWORK=3.1.*
  - SYMFONY_FRAMEWORK=3.2.*
  - SYMFONY_FRAMEWORK=3.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_FWK_BUNDLE_VERSION}
  - composer install -o
