language: php

php: [5.5, 5.6, 7.0, 7.1]

env:
  - SYMFONY_FRAMEWORK=2.0.*
  - SYMFONY_FRAMEWORK=2.1.*
  - SYMFONY_FRAMEWORK=2.2.*
  - SYMFONY_FRAMEWORK=2.3.*
  - SYMFONY_FRAMEWORK=2.4.*
  - SYMFONY_FRAMEWORK=2.5.*
  - SYMFONY_FRAMEWORK=2.6.*
  - SYMFONY_FRAMEWORK=2.7.*
  - SYMFONY_FRAMEWORK=2.8.*
  - SYMFONY_FRAMEWORK=3.0.*
  - SYMFONY_FRAMEWORK=3.1.*
  - SYMFONY_FRAMEWORK=3.2.*
  - SYMFONY_FRAMEWORK=3.3.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_FRAMEWORK}
  - composer install -o

script:
  - ./vendor/bin/phpunit
